stages:
  Download:
    cmd: python src/download.py
    params:
    - n_locs
    - seed
    - year
    outs:
    - data/csv
  Prepare:
    cmd: python src/prepare.py
    deps:
    - data/csv
    - src/download.py
    params:
    - year
    outs:
    - data/prepared
